'use client'
/**
 * DataGraphsLesson (9–11) — reading bar charts and pictographs: find a bar's
 * value, compare most/least, how-many-more, and totals. In a pictograph each
 * picture stands for several (the key). Built on the shared kit (centered
 * Retry+Next pop-up, no celebration slides). See docs/curriculum-9-11.md.
 */
import React, { useState, useEffect, useRef } from 'react'
import { speak, speakSeq } from '@/lib/useMiloSpeaker'
import { LessonScaffold, Confetti, type LessonStep } from './_kit'

// ─── Shared data model (also generated by the chapter) ─────────
export interface ChartCategory { label: string; emoji: string; value: number }
export interface ChartData {
  kind: 'bar' | 'picto'
  unit: string                 // plural noun counted ("votes", "books")
  categories: ChartCategory[]
  perSymbol?: number           // pictograph key: each picture = perSymbol
}
export interface ChartQuestion {
  chart: ChartData
  ask: string
  reveal: string               // spoken sentence stating the answer
  answer: string               // category label OR a number as a string
  choices: string[]
  highlight: string[]          // category labels to emphasise on reveal
}

const BAR_COLORS = ['var(--milo-orange)', 'var(--sky-blue-deep)', 'var(--garden-green)', 'var(--apple-red)']

// ─── The chart itself (bar or pictograph), reused everywhere ───
export function ChartView({ chart, highlight, dim }: { chart: ChartData; highlight?: string[]; dim?: boolean }) {
  const on = (label: string) => !highlight || highlight.length === 0 || highlight.includes(label)
  if (chart.kind === 'picto') {
    const per = chart.perSymbol ?? 1
    const sym = chart.categories[0]?.emoji ?? '⭐'
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10, alignItems: 'center' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {chart.categories.map((c, i) => (
            <div key={c.label} style={{ display: 'flex', alignItems: 'center', gap: 8, opacity: dim && !on(c.label) ? 0.4 : 1, transition: 'opacity 0.3s' }}>
              <span style={{ width: 64, textAlign: 'right', fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 14, color: 'var(--ink)' }}>{c.label}</span>
              <div style={{ display: 'flex', gap: 2, padding: '4px 8px', borderRadius: 10, minHeight: 28, alignItems: 'center', background: on(c.label) ? 'var(--sky-blue-soft)' : 'transparent' }}>
                {Array.from({ length: Math.round(c.value / per) }).map((_, j) => (
                  <span key={j} style={{ fontSize: 20, animation: `k_dropIn 0.35s ease ${(i * 4 + j) * 0.05}s both` }}>{c.emoji}</span>
                ))}
              </div>
            </div>
          ))}
        </div>
        <div style={{ fontFamily: 'var(--font-body)', fontWeight: 700, fontSize: 13, color: 'var(--ink-soft)', background: 'var(--paper)', border: '2px solid var(--outline)', borderRadius: 10, padding: '4px 12px' }}>
          Key: each {sym} = {per} {chart.unit}
        </div>
      </div>
    )
  }
  const maxVal = Math.max(...chart.categories.map(c => c.value), 1)
  return (
    <div style={{ display: 'flex', alignItems: 'flex-end', gap: 16, justifyContent: 'center', minHeight: 180, padding: '0 6px' }}>
      {chart.categories.map((c, i) => {
        const h = Math.round(24 + (c.value / maxVal) * 130)
        const active = on(c.label)
        return (
          <div key={c.label} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, opacity: dim && !active ? 0.4 : 1, transition: 'opacity 0.3s' }}>
            <span style={{ fontFamily: 'var(--font-display)', fontWeight: 900, fontSize: 18, color: 'var(--ink)' }}>{c.value}</span>
            <div style={{
              width: 42, height: h, borderRadius: '10px 10px 4px 4px',
              background: BAR_COLORS[i % BAR_COLORS.length], border: '3px solid var(--outline)',
              boxShadow: active ? '0 0 0 3px var(--milo-yellow,transparent)' : 'none',
              animation: `k_dropIn 0.45s ease ${i * 0.08}s both`,
            }} />
            <span style={{ fontSize: 22 }}>{c.emoji}</span>
            <span style={{ fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 12, color: 'var(--ink-soft)', maxWidth: 56, textAlign: 'center', lineHeight: 1.1 }}>{c.label}</span>
          </div>
        )
      })}
    </div>
  )
}

// ─── Worked example: read the chart, then reveal the answer ────
export function ChartWatch({ q, intro, outro, onDone }: { q: ChartQuestion; intro: string; outro: string; onDone: () => void }) {
  const [show, setShow] = useState(false)   // answer revealed → highlight + badge
  const ran = useRef(false)
  useEffect(() => {
    if (ran.current) return
    ran.current = true
    const lines = [intro, q.ask, q.reveal, outro]
    let started = false, finished = false
    const cl: Array<() => void> = []
    const at = (fn: () => void, ms: number) => { const id = window.setTimeout(fn, ms); cl.push(() => window.clearTimeout(id)) }
    const complete = () => { if (finished) return; finished = true; at(onDone, 900) }
    const cancel = speakSeq(lines, { onWord: i => { started = true; if (i >= 2) setShow(true) }, onDone: complete })
    cl.push(cancel)
    at(() => {
      if (started || finished) return
      cancel()
      let t = 0
      at(() => speak(lines[1]), t); t += 2600
      at(() => { setShow(true); speak(lines[2]) }, t); t += 2600
      at(() => { speak(outro); complete() }, t)
    }, 1900)
    return () => cl.forEach(f => f())
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14, position: 'relative' }}>
      {show && <Confetti />}
      <ChartView chart={q.chart} highlight={show ? q.highlight : []} dim={show} />
      <div style={{ fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 17, color: 'var(--ink)', textAlign: 'center', maxWidth: 380 }}>{q.ask}</div>
      {show && (
        <div style={{ fontFamily: 'var(--font-display)', fontWeight: 900, fontSize: 28, color: 'var(--garden-green-deep)', animation: 'k_countBadge 0.4s cubic-bezier(.34,1.56,.64,1)' }}>{q.answer}</div>
      )}
    </div>
  )
}

// ─── Interactive: read the chart, pick the answer ─────────────
export function ChartPick({ q, intro, outro, onDone }: { q: ChartQuestion; intro: string; outro: string; onDone: () => void }) {
  const [picked, setPicked] = useState<string | null>(null)
  const [wrong, setWrong] = useState<string | null>(null)
  const [ready, setReady] = useState(false)
  const ran = useRef(false)
  useEffect(() => {
    if (ran.current) return; ran.current = true
    speak(`${intro} ${q.ask}`)
    const id = window.setTimeout(() => setReady(true), 700)
    return () => window.clearTimeout(id)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  function pick(c: string) {
    if (picked != null || !ready) return
    if (c === q.answer) { setPicked(c); setWrong(null); speak(outro); window.setTimeout(onDone, 1900) }
    else { setWrong(c); speak('Not quite — look at the chart again.'); window.setTimeout(() => setWrong(null), 1100) }
  }
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14 }}>
      <ChartView chart={q.chart} highlight={picked ? q.highlight : []} dim={picked != null} />
      <div style={{ fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 16, color: 'var(--ink)', textAlign: 'center', maxWidth: 380 }}>{q.ask}</div>
      <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap', opacity: ready ? 1 : 0.5, transition: 'opacity 0.2s' }}>
        {q.choices.map(c => {
          const isRight = picked === c, isWrong = wrong === c
          return (
            <button key={c} onClick={() => pick(c)} disabled={picked != null || !ready} style={{
              minWidth: 80, height: 72, padding: '0 14px', borderRadius: 20,
              background: isRight ? 'var(--garden-green-soft)' : 'var(--paper)',
              border: `4px solid ${isRight ? 'var(--garden-green)' : isWrong ? 'var(--ink-muted)' : 'var(--outline)'}`,
              boxShadow: isRight ? '0 6px 0 var(--garden-green-deep)' : '0 6px 0 #c8ac79',
              fontFamily: 'var(--font-display)', fontWeight: 900, fontSize: 24, color: 'var(--ink)',
              cursor: picked != null || !ready ? 'default' : 'pointer',
            }}>{c}</button>
          )
        })}
      </div>
    </div>
  )
}

// ─── Steps ───────────────────────────────────────────────────
interface Props { childName: string; onLessonComplete: () => void }

const fruitBar: ChartData = { kind: 'bar', unit: 'votes', categories: [
  { label: 'Apple', emoji: '🍎', value: 5 }, { label: 'Banana', emoji: '🍌', value: 8 }, { label: 'Cherry', emoji: '🍒', value: 3 },
] }
const petBar: ChartData = { kind: 'bar', unit: 'pets', categories: [
  { label: 'Dogs', emoji: '🐶', value: 6 }, { label: 'Cats', emoji: '🐱', value: 9 }, { label: 'Fish', emoji: '🐟', value: 4 }, { label: 'Birds', emoji: '🐦', value: 2 },
] }
const starPicto: ChartData = { kind: 'picto', unit: 'stars', perSymbol: 2, categories: [
  { label: 'Mon', emoji: '⭐', value: 6 }, { label: 'Tue', emoji: '⭐', value: 4 }, { label: 'Wed', emoji: '⭐', value: 10 },
] }

function buildSteps(childName: string): LessonStep[] {
  return [
    { bubble: `Hi ${childName}! A bar chart shows amounts. Taller means more. 📊`, mood: 'happy',
      render: d => <ChartWatch q={{ chart: fruitBar, ask: 'How many votes did 🍌 Banana get?', reveal: 'Banana got eight votes — read the number on top.', answer: '8', choices: ['5', '8', '3'], highlight: ['Banana'] }}
        intro={`Hi ${childName}! Each bar is a fruit. Read the number on top.`} outro="The taller the bar, the more votes!" onDone={d} /> },
    { bubble: 'The tallest bar is the most! 🏆', mood: 'thinking',
      render: d => <ChartWatch q={{ chart: fruitBar, ask: 'Which fruit got the MOST votes?', reveal: 'Banana — it has the tallest bar.', answer: 'Banana', choices: ['Apple', 'Banana', 'Cherry'], highlight: ['Banana'] }}
        intro="Look for the tallest bar." outro="Tallest bar wins!" onDone={d} /> },
    { bubble: 'The shortest bar is the least. 🔎', mood: 'thinking',
      render: d => <ChartWatch q={{ chart: petBar, ask: 'Which pet is the LEAST popular?', reveal: 'Birds — the shortest bar, only two.', answer: 'Birds', choices: ['Dogs', 'Fish', 'Birds'], highlight: ['Birds'] }}
        intro="Now find the shortest bar." outro="Shortest bar is the least!" onDone={d} /> },
    { bubble: '"How many more?" means subtract. ➖', mood: 'thinking',
      render: d => <ChartWatch q={{ chart: petBar, ask: 'How many MORE cats than dogs? (9 and 6)', reveal: 'Nine take away six is three more cats.', answer: '3', choices: ['3', '15', '6'], highlight: ['Cats', 'Dogs'] }}
        intro="Cats are nine, dogs are six. Take away to compare." outro="Nine minus six is three!" onDone={d} /> },
    { bubble: 'Your turn — read the chart! 👂', mood: 'thinking',
      render: d => <ChartPick q={{ chart: petBar, ask: 'How many dogs are there?', reveal: '', answer: '6', choices: ['6', '9', '4'], highlight: ['Dogs'] }}
        intro="Read the number above the dogs' bar." outro="Yes! Six dogs!" onDone={d} /> },
    { bubble: 'A pictograph uses pictures — each one counts for more! 🖼️', mood: 'happy',
      render: d => <ChartWatch q={{ chart: starPicto, ask: 'How many stars on Wednesday? Each ⭐ = 2.', reveal: 'Five pictures, and each is two — that is ten.', answer: '10', choices: ['5', '10', '8'], highlight: ['Wed'] }}
        intro="Each picture stands for two. Count the pictures, then times by two." outro="Five twos make ten!" onDone={d} /> },
    { bubble: 'Last one — use the key! 🏆', mood: 'thinking',
      render: d => <ChartPick q={{ chart: starPicto, ask: 'How many stars on Monday? Each ⭐ = 2.', reveal: '', answer: '6', choices: ['3', '6', '8'], highlight: ['Mon'] }}
        intro="Three pictures, each worth two." outro="Amazing! Three twos are six!" onDone={d} /> },
  ]
}

export default function DataGraphsLesson({ childName, onLessonComplete }: Props) {
  return (
    <LessonScaffold
      childName={childName}
      onLessonComplete={onLessonComplete}
      steps={buildSteps(childName)}
      finalSpeech={`Great reading, ${childName}! Now let's read some charts together!`}
    />
  )
}
