'use client'
/**
 * WordProblemsLesson (9–11) — multi-step, mixed-operation word problems. The
 * child learns a plan: read the story, find the numbers, do it one step at a
 * time. Each worked example reveals the steps (e.g. "× then −") one at a time,
 * then the answer. Built on the shared kit (centered Retry+Next pop-up, no
 * celebration slides). See docs/curriculum-9-11.md.
 */
import React, { useState, useEffect, useRef } from 'react'
import { speak, speakSeq } from '@/lib/useMiloSpeaker'
import { nounFor } from '@/lib/grammar'
import { LessonScaffold, Confetti, type LessonStep } from './_kit'

// ─── Shared problem model (also generated by the chapter) ──────
export interface WordStep { say: string; expr: string }
export interface WordProblem {
  scene: string          // the story, read aloud + shown
  emoji: string
  steps: WordStep[]      // one line per step, expr already includes "= result"
  answer: number
  unit: string           // plural noun for the answer ("apples", "coins")
}

function SceneCard({ emoji, scene }: { emoji: string; scene: string }) {
  return (
    <div style={{ display: 'flex', gap: 10, alignItems: 'flex-start', background: 'var(--paper)', border: '3px solid var(--outline)', borderRadius: 18, padding: '12px 16px', maxWidth: 420, boxShadow: '0 4px 0 rgba(61,37,22,.08)' }}>
      <span style={{ fontSize: 30, lineHeight: 1.1, flexShrink: 0 }}>{emoji}</span>
      <span style={{ fontFamily: 'var(--font-body)', fontWeight: 600, fontSize: 17, color: 'var(--ink)', lineHeight: 1.4 }}>{scene}</span>
    </div>
  )
}

// ─── Worked example: reveal each step, then the answer ─────────
export function SolveWatch({ problem, intro, outro, onDone }: { problem: WordProblem; intro: string; outro: string; onDone: () => void }) {
  const [revealed, setRevealed] = useState(0)   // # of step cards shown
  const [showAns, setShowAns] = useState(false)
  const ran = useRef(false)
  useEffect(() => {
    if (ran.current) return
    ran.current = true
    const lines = [intro, problem.scene, ...problem.steps.map(s => s.say), outro]
    const lastStepLine = 1 + problem.steps.length   // index of the final step's line
    let started = false, finished = false
    const cl: Array<() => void> = []
    const at = (fn: () => void, ms: number) => { const id = window.setTimeout(fn, ms); cl.push(() => window.clearTimeout(id)) }
    const apply = (i: number) => {
      if (i >= 2 && i < 2 + problem.steps.length) setRevealed(i - 1)
      if (i >= lastStepLine) setShowAns(true)
    }
    const complete = () => { if (finished) return; finished = true; at(onDone, 900) }
    const cancel = speakSeq(lines, { onWord: i => { started = true; apply(i) }, onDone: complete })
    cl.push(cancel)
    at(() => {
      if (started || finished) return
      cancel()
      let t = 0
      at(() => { speak(lines[1]) }, t); t += 2800
      problem.steps.forEach((s, k) => {
        at(() => { setRevealed(k + 1); if (k === problem.steps.length - 1) setShowAns(true); speak(s.say) }, t); t += 2800
      })
      at(() => { speak(outro); complete() }, t)
    }, 1900)
    return () => cl.forEach(f => f())
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14, position: 'relative' }}>
      {showAns && <Confetti />}
      <SceneCard emoji={problem.emoji} scene={problem.scene} />
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8, alignItems: 'center' }}>
        {problem.steps.map((s, k) => (
          <div key={k} style={{
            opacity: revealed > k ? 1 : 0, transform: revealed > k ? 'translateY(0)' : 'translateY(8px)',
            transition: 'all 0.35s ease', display: 'flex', alignItems: 'center', gap: 8,
            background: 'var(--sky-blue-soft)', border: '3px solid var(--sky-blue-deep)', borderRadius: 14, padding: '8px 16px',
            fontFamily: 'var(--font-display)', fontWeight: 900, fontSize: 24, color: 'var(--ink)',
          }}>
            <span style={{ fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 13, color: 'var(--sky-blue-deep)' }}>Step {k + 1}</span>
            {s.expr}
          </div>
        ))}
      </div>
      {showAns && (
        <div style={{ fontFamily: 'var(--font-display)', fontWeight: 900, fontSize: 30, color: 'var(--garden-green-deep)', animation: 'k_countBadge 0.4s cubic-bezier(.34,1.56,.64,1)' }}>
          {problem.answer} {nounFor(problem.answer, problem.unit)}!
        </div>
      )}
    </div>
  )
}

// ─── Interactive: read the story, pick the final answer ────────
export function WordPick({ problem, choices, intro, outro, onDone }: { problem: WordProblem; choices: number[]; intro: string; outro: string; onDone: () => void }) {
  const [picked, setPicked] = useState<number | null>(null)
  const [wrong, setWrong] = useState<number | null>(null)
  const [ready, setReady] = useState(false)
  const ran = useRef(false)
  useEffect(() => {
    if (ran.current) return; ran.current = true
    speak(`${intro} ${problem.scene}`)
    const id = window.setTimeout(() => setReady(true), 700)
    return () => window.clearTimeout(id)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  function pick(c: number) {
    if (picked != null || !ready) return
    if (c === problem.answer) { setPicked(c); setWrong(null); speak(outro); window.setTimeout(onDone, 1900) }
    else { setWrong(c); speak('Not quite — do it one step at a time, then count.'); window.setTimeout(() => setWrong(null), 1100) }
  }
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
      <SceneCard emoji={problem.emoji} scene={problem.scene} />
      <button onClick={() => speak(problem.scene)} style={{ background: 'var(--paper)', border: '3px solid var(--outline)', borderRadius: 999, padding: '6px 16px', fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 14, color: 'var(--ink)', cursor: 'pointer', boxShadow: '0 3px 0 rgba(61,37,22,.12)' }}>🔊 Read it again</button>
      <div style={{ display: 'flex', gap: 14, justifyContent: 'center', flexWrap: 'wrap', opacity: ready ? 1 : 0.5, transition: 'opacity 0.2s' }}>
        {choices.map(c => {
          const isRight = picked === c, isWrong = wrong === c
          return (
            <button key={c} onClick={() => pick(c)} disabled={picked != null || !ready} style={{
              minWidth: 88, height: 80, padding: '0 12px', borderRadius: 22,
              background: isRight ? 'var(--garden-green-soft)' : isWrong ? 'var(--paper)' : 'var(--paper)',
              border: `4px solid ${isRight ? 'var(--garden-green)' : isWrong ? 'var(--ink-muted)' : 'var(--outline)'}`,
              boxShadow: isRight ? '0 6px 0 var(--garden-green-deep)' : '0 6px 0 #c8ac79',
              fontFamily: 'var(--font-display)', fontWeight: 900, fontSize: 30, color: 'var(--ink)',
              cursor: picked != null || !ready ? 'default' : 'pointer',
            }}>{c}</button>
          )
        })}
      </div>
    </div>
  )
}

// ─── Steps ───────────────────────────────────────────────────
interface Props { childName: string; onLessonComplete: () => void }

const P = {
  packs: { scene: 'Milo buys 3 packs of 4 apples, then gives 5 apples away. How many apples are left?', emoji: '🍎',
    steps: [{ say: 'First, 3 packs of 4 is 12.', expr: '3 × 4 = 12' }, { say: 'Then give 5 away. 12 minus 5 is 7.', expr: '12 − 5 = 7' }], answer: 7, unit: 'apples' },
  coins: { scene: 'Mia has 8 coins, earns 6 more, then spends 5. How many coins now?', emoji: '🪙',
    steps: [{ say: 'First, 8 plus 6 is 14.', expr: '8 + 6 = 14' }, { say: 'Then spend 5. 14 minus 5 is 9.', expr: '14 − 5 = 9' }], answer: 9, unit: 'coins' },
  garden: { scene: 'A garden has 5 rows of 6 flowers. A bee visits 4 flowers. How many flowers are NOT visited?', emoji: '🌸',
    steps: [{ say: 'First, 5 rows of 6 is 30.', expr: '5 × 6 = 30' }, { say: 'Take away the 4 visited. 30 minus 4 is 26.', expr: '30 − 4 = 26' }], answer: 26, unit: 'flowers' },
  pages: { scene: 'Sam reads 7 pages each day for 4 days, then 3 more pages. How many pages in all?', emoji: '📚',
    steps: [{ say: 'First, 7 pages for 4 days is 28.', expr: '7 × 4 = 28' }, { say: 'Then add 3 more. 28 plus 3 is 31.', expr: '28 + 3 = 31' }], answer: 31, unit: 'pages' },
  bags: { scene: 'Milo shares 20 marbles into 4 bags equally, then loses 3 from one bag. How many marbles in that bag now?', emoji: '🔵',
    steps: [{ say: 'Share 20 into 4 bags — that is 5 each.', expr: '20 ÷ 4 = 5' }, { say: 'Then lose 3. 5 minus 3 is 2.', expr: '5 − 3 = 2' }], answer: 2, unit: 'marbles' },
} satisfies Record<string, WordProblem>

function buildSteps(childName: string): LessonStep[] {
  return [
    { bubble: `Hi ${childName}! Big problems have little steps. Let's solve them one at a time. 🧩`, mood: 'happy',
      render: d => <SolveWatch problem={P.packs} intro={`Hi ${childName}! Listen to the whole story first.`} outro="Two little steps — that's it!" onDone={d} /> },
    { bubble: 'Find the numbers, then pick what to do. ➕➖', mood: 'thinking',
      render: d => <SolveWatch problem={P.coins} intro="Add what comes in, take away what goes out." outro="Step by step — nice!" onDone={d} /> },
    { bubble: 'Rows make groups — that means times! ✖️', mood: 'thinking',
      render: d => <SolveWatch problem={P.garden} intro="Rows of the same amount — that's multiplying." outro="Multiply, then subtract!" onDone={d} /> },
    { bubble: 'Each day the same — multiply, then add the extra. 📚', mood: 'thinking',
      render: d => <SolveWatch problem={P.pages} intro="Same amount each day is multiplying." outro="Multiply, then add!" onDone={d} /> },
    { bubble: 'Your turn — solve it in your head, one step at a time! 👂', mood: 'thinking',
      render: d => <WordPick problem={P.coins} choices={[9, 14, 19]} intro="Listen, then pick the answer." outro="Yes! Add 6, then take away 5 — nine!" onDone={d} /> },
    { bubble: 'Sharing equally means dividing. ➗', mood: 'happy',
      render: d => <SolveWatch problem={P.bags} intro="Shared equally — that's dividing." outro="Divide, then subtract!" onDone={d} /> },
    { bubble: 'Last one — read it, then choose! 🏆', mood: 'thinking',
      render: d => <WordPick problem={P.packs} choices={[7, 12, 17]} intro="Here's the story." outro="Amazing! Three fours is twelve, take five — seven!" onDone={d} /> },
  ]
}

export default function WordProblemsLesson({ childName, onLessonComplete }: Props) {
  return (
    <LessonScaffold
      childName={childName}
      onLessonComplete={onLessonComplete}
      steps={buildSteps(childName)}
      finalSpeech={`Great thinking, ${childName}! Now let's solve some together!`}
    />
  )
}
